//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int InstructorID { get; set; }
        public string Fname { get; set; }
        public string lname { get; set; }
        public int Salary { get; set; }
    }
}
