//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class material
    {
        public int ID { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public Nullable<int> courseID { get; set; }
        public HttpPostedFileBase UploadMaterial { get; set; }
        public string courseName { get; set; }  
        public virtual Course Course { get; set; }
    }
}
