//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class Note
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string status { get; set; }
        public int author { get; set; }
        public string courseName { get; set; }
        public HttpPostedFileBase UploadFile { get; set; }  
        public virtual Login Login { get; set; }
    }
}
