//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int ID { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> Explanation { get; set; }
        public Nullable<int> Content { get; set; }
        public Nullable<int> Relevance { get; set; }
        public string Comment { get; set; }
        
        public string CourseName { get; set; }
        public virtual Course Course { get; set; }
    }
}
