//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YRPortal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Task
    {
        public int id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        [DataType(DataType.Date)]
        public System.DateTime deadline { get; set; }
        public Nullable<int> StudentID { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
